package ratph6.tessera.engine

import com.caoccao.javet.swc4j.Swc4j
import com.caoccao.javet.swc4j.enums.Swc4jMediaType
import com.caoccao.javet.swc4j.enums.Swc4jModuleKind
import com.caoccao.javet.swc4j.enums.Swc4jParseMode
import com.caoccao.javet.swc4j.enums.Swc4jSourceMapOption
import com.caoccao.javet.swc4j.options.Swc4jTranspileOptions
import org.graalvm.polyglot.Context
import org.graalvm.polyglot.Engine
import org.graalvm.polyglot.HostAccess
import org.graalvm.polyglot.Source
import org.graalvm.polyglot.Value
import java.net.URI
import java.nio.file.Path

/**
 * The GraalJS execution engine — the "real JavaScript" path. A Tessera module's TypeScript is first
 * transpiled to JavaScript by swc4j (here used as a plain TS→JS transpiler, *not* its bytecode
 * compiler) and then evaluated as an ES module on a GraalJS [Context]. Scripts get full ECMAScript:
 * real arrays with `.map`/`.filter`, closures over reassigned `let`s, objects, JSON, etc. — none of
 * the bytecode path's "half-Java" workarounds (`Store`/`Num`/`Args`).
 *
 * The Tessera API objects (`Tessera`, `Event`, `ChatLib`, ...) are bound as JS globals, so the familiar
 * `import { Tessera, Event } from 'ratph6.tessera.api'` line is simply stripped before evaluation (the names
 * resolve to the globals instead).
 *
 * Single-threaded by construction: the [Context] is created on, and only ever touched from, the JS
 * thread — which is also where module loading, dispatch and timers run. This matches GraalJS's
 * single-thread-at-a-time contract; no locking needed.
 *
 * Security: host access is broad on the *bound* objects, but `allowHostClassLookup` is left off, so
 * guest code cannot reach `Runtime`/`ProcessBuilder`/etc. — only the bound API surface and whatever
 * it returns. Mirrors the intent of [TesseraCompiler]'s import ban.
 */
object GraalRuntime {

    private val log = org.slf4j.LoggerFactory.getLogger("Tessera")
    private val swc4j = Swc4j()

    @Volatile private var engine: Engine? = null
    @Volatile private var ctx: Context? = null

    private fun engine(): Engine = engine ?: synchronized(this) {
        engine ?: Engine.newBuilder("js")
            .option("engine.WarnInterpreterOnly", "false")
            .build().also { engine = it }
    }

    /**
     * Tessera API names → fully-qualified class name. Exposed to scripts the same way Minecraft classes
     * are: usable with no import, and also bound when a script `import`s them. The API objects are
     * Kotlin `object`s with `@JvmStatic` methods (compiled to *statics*), so they're reached via
     * `Java.type('<fqcn>')` — a host *type* whose static methods/fields are members (`Tessera.register`,
     * `ChatLib.chat`, `Event.CHAT`); binding the bare `Class` would expose `java.lang.Class` instead.
     */
    private val tesseraApi: Map<String, String> = listOf(
        "Tessera", "ChatLib", "Player", "World", "Renderer", "Tessellator", "PlayerScales",
        "Num", "Args", "Store", "Server", "TabList", "Scoreboard", "KeyBind",
        "Event", "Display", "CancellableEvent", "Mixin", "MixinContext", "AccessWidener",
    ).associateWith { "ratph6.tessera.api.$it" }

    /** name → FQCN for unique-named Minecraft classes (generated by genMinecraftDts), usable with no import. */
    private val mcGlobals: Map<String, String> by lazy { loadMcGlobals() }

    /** Every name a script may use without importing: Tessera API + unique Minecraft classes (Tessera wins ties). */
    private val globals: Map<String, String> by lazy { mcGlobals + tesseraApi }

    private fun loadMcGlobals(): Map<String, String> = runCatching {
        GraalRuntime::class.java.getResourceAsStream("/tessera/minecraft-globals.json")?.use { ins ->
            val type = object : com.google.gson.reflect.TypeToken<Map<String, String>>() {}.type
            com.google.gson.Gson().fromJson<Map<String, String>>(java.io.InputStreamReader(ins, Charsets.UTF_8), type)
        }
    }.getOrNull() ?: emptyMap()

    /**
     * Host access = everything in [HostAccess.ALL] plus number→`float` coercions. GraalJS hands a JS
     * number to Java as a `double`/`int`/`long`; without these mappings, calling any Java method with a
     * `float` parameter (Minecraft has hundreds — `setYRot`, `setXRot`, render/pose calls, …) throws
     * "Invalid or lossy primitive coercion". The mappings narrow the value so those calls just work.
     */
    internal val hostAccess: HostAccess by lazy {
        HostAccess.newBuilder(HostAccess.ALL)
            .targetTypeMapping(Double::class.javaObjectType, Float::class.javaObjectType, { true }, { it.toFloat() })
            .targetTypeMapping(Integer::class.javaObjectType, Float::class.javaObjectType, { true }, { it.toFloat() })
            .targetTypeMapping(java.lang.Long::class.javaObjectType, Float::class.javaObjectType, { true }, { it.toFloat() })
            .build()
    }

    /** The lazily-built JS context. Built on the calling (JS) thread; only ever touched from it. */
    private fun context(): Context {
        ctx?.let { return it }
        val c = Context.newBuilder("js")
            .engine(engine())
            .allowHostAccess(hostAccess)
            // Allow `Java.type` only for the Tessera API and Minecraft — `java.lang.Runtime` & friends stay
            // refused. (Mojang-mapped names resolve in the dev client; a remapped prod jar would not.)
            .allowHostClassLookup { it.startsWith("ratph6.tessera.api.") || it.startsWith("net.minecraft.") }
            // Resolve `Java.type(...)` against the loader that sees those classes (Fabric's Knot loader in-game).
            .hostClassLoader(GraalRuntime::class.java.classLoader)
            .allowExperimentalOptions(true)
            .option("js.ecmascript-version", "2024")
            .build()
        bootstrapJs(c)
        ctx = c
        return c
    }

    /**
     * Install the standard timer/async globals once per context, backed by Tessera's tick-thread timers.
     * This is what makes `async`/`await` actually progress: `await sleep(ms)` schedules a Tessera timer
     * that fires on the JS thread, resolves the promise, and GraalJS then drains the microtask queue —
     * resuming the awaiting function. Also gives scripts the familiar `setTimeout`/`setInterval`.
     */
    private fun bootstrapJs(c: Context) {
        runCatching {
            c.eval(
                "js",
                """
                const __Tessera = Java.type('ratph6.tessera.api.Tessera');
                globalThis.setTimeout = (fn, ms) => __Tessera.setTimeout(fn, (ms | 0));
                globalThis.setInterval = (fn, ms) => __Tessera.setInterval(fn, (ms | 0));
                globalThis.clearTimeout = (id) => __Tessera.clearTimer(id | 0);
                globalThis.clearInterval = (id) => __Tessera.clearTimer(id | 0);
                globalThis.sleep = (ms) => new Promise((resolve) => __Tessera.setTimeout(resolve, (ms | 0)));
                """.trimIndent(),
            )
        }.onFailure { log.warn("graal async bootstrap failed ({})", it.toString()) }
    }

    private fun mediaTypeFor(fileName: String): Swc4jMediaType =
        when (fileName.substringAfterLast('.', "").lowercase()) {
            "tsx" -> Swc4jMediaType.Tsx
            "jsx" -> Swc4jMediaType.Jsx
            "js", "mjs", "cjs" -> Swc4jMediaType.JavaScript
            else -> Swc4jMediaType.TypeScript
        }

    /** Transpile TypeScript (or JS) [source] to plain ES-module JavaScript. */
    fun transpileTs(source: String, fileName: String): String {
        val options = Swc4jTranspileOptions()
            .setSpecifier(URI.create("file:///$fileName").toURL())
            .setMediaType(mediaTypeFor(fileName))
            .setParseMode(Swc4jParseMode.Module)
            .setModuleKind(Swc4jModuleKind.Esm)
            .setSourceMap(Swc4jSourceMapOption.None)
        return swc4j.transpile(source, options).code
    }

    // --- import + global resolution ---------------------------------------------------------------
    // Tessera modules are single-file; their `import { X, Y } from 'spec'` lines have no JS module to
    // resolve, so each is rewritten to `const X = Java.type('spec.X')` (works for Tessera + Minecraft).
    private val braceImport = Regex("""import\s*\{([^}]*)\}\s*from\s*['"]([^'"]+)['"]\s*;?""")
    private val identifier = Regex("""[A-Za-z_$][A-Za-z0-9_$]*""")
    private val asSplit = Regex("""\s+as\s+""")

    /** Rewrite brace imports to `Java.type` consts; returns the new source and the names it bound. */
    private fun rewriteImports(js: String): Pair<String, Set<String>> {
        val bound = HashSet<String>()
        val out = braceImport.replace(js) { m ->
            val spec = m.groupValues[2]
            m.groupValues[1].split(',').mapNotNull { raw ->
                val parts = raw.trim().split(asSplit)
                val orig = parts[0].trim()
                if (orig.isEmpty()) return@mapNotNull null
                val local = (parts.getOrNull(1) ?: orig).trim()
                bound.add(local)
                "const $local = Java.type('$spec.$orig');"
            }.joinToString(" ")
        }
        return out to bound
    }

    /** Bind every no-import global the script actually references (and didn't import) to its host type. */
    private fun globalsPrelude(js: String, alreadyBound: Set<String>): String {
        val used = identifier.findAll(js).mapTo(HashSet()) { it.value }
        val sb = StringBuilder()
        for ((name, fqcn) in globals) {
            if (name !in alreadyBound && name in used) {
                sb.append("const ").append(name).append(" = Java.type('").append(fqcn).append("');\n")
            }
        }
        return sb.toString()
    }

    /** Transpile, resolve `import`s, and prepend bindings for referenced no-import globals. */
    private fun prepare(source: String, fileName: String): String {
        val (rewritten, bound) = rewriteImports(transpileTs(source, fileName))
        return globalsPrelude(rewritten, bound) + rewritten
    }

    /**
     * Transpile + evaluate a module's TypeScript as an ES module. Top-level code runs immediately
     * (so top-level `Tessera.register(...)` calls register against [module]); the returned namespace holds
     * any exported functions (for the `main`/`init` entry and trigger-name conventions).
     */
    fun loadModule(manifest: TesseraManifest, dir: Path, source: String): GraalModule {
        val js = prepare(source, "${manifest.name}/${manifest.entry}")
        val module = GraalModule(manifest, dir)
        val c = context()
        TesseraEngine.withCurrentModule(module) {
            val src = Source.newBuilder("js", js, "${manifest.name}.mjs")
                .mimeType("application/javascript+module")
                .build()
            module.attach(c.eval(src))
        }
        return module
    }

    /** Transpile + run a one-off snippet as a script (for `/te eval`). Tessera + Minecraft names need no import. */
    fun evalSnippet(code: String): Value {
        val js = prepare(code, "tessera-eval.ts")
        return TesseraEngine.withCurrentModule(null) { context().eval("js", js) }
    }

    /** Dispose the context so a reload starts from clean JS global state. Next load rebuilds it. */
    fun reset() {
        synchronized(this) {
            runCatching { ctx?.close(true) }.onFailure { log.warn("graal context close failed ({})", it.toString()) }
            ctx = null
        }
    }
}
