package ratph6.tessera.client

import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption

// first-run setup of .minecraft/tessera/: refresh tessera.d.ts, and drop the hello-tessera example if modules dir is empty
object TesseraScaffold {
    private val exampleFiles = listOf("hello-tessera/tessera.json", "hello-tessera/index.ts")

    fun install(tesseraDir: Path) {
        runCatching {
            Files.createDirectories(tesseraDir)
            copyResource("/tessera/types/tessera.d.ts", tesseraDir.resolve("tessera.d.ts"))

            val modulesDir = tesseraDir.resolve("modules")
            val isEmpty = !Files.exists(modulesDir) ||
                Files.list(modulesDir).use { stream -> stream.findAny().isEmpty }
            Files.createDirectories(modulesDir)
            if (isEmpty) {
                for (rel in exampleFiles) {
                    val dest = modulesDir.resolve(rel)
                    Files.createDirectories(dest.parent)
                    copyResource("/tessera/examples/$rel", dest)
                }
            }
        }
    }

    private fun copyResource(resource: String, dest: Path) {
        TesseraScaffold::class.java.getResourceAsStream(resource)?.use {
            Files.copy(it, dest, StandardCopyOption.REPLACE_EXISTING)
        }
    }

    // fails if the folder already exists so we never clobber an existing module
    fun createModule(modulesDir: Path, name: String): Result<Path> = runCatching {
        val dir = modulesDir.resolve(name)
        require(!Files.exists(dir)) { "module '$name' already exists" }
        Files.createDirectories(dir)
        Files.writeString(dir.resolve("tessera.json"), manifestTemplate(name))
        Files.writeString(dir.resolve("index.ts"), entryTemplate(name))
        dir
    }

    private fun manifestTemplate(name: String) = """
        {
          "name": "$name",
          "version": "1.0.0",
          "author": "you",
          "description": "$name — a Tessera module.",
          "entry": "index.ts",
          "engine": "graal"
        }
    """.trimIndent() + "\n"

    private fun entryTemplate(name: String) = """
        // $name — generated by /te create. Edit, then /te reload in game.

        import { Tessera, Event, ChatLib, Player } from 'ratph6.tessera.api';

        ChatLib.chat("§a[$name] loaded! Say something containing 'ping', or run /$name.");

        Tessera.register(Event.CHAT, (message) => {
          ChatLib.chat("§epong!");
        }).setContains().setCriteria("ping");

        Tessera.register(Event.COMMAND, (args) => {
          ChatLib.chat("§b[$name] XYZ: " + Player.getX() + ", " + Player.getY() + ", " + Player.getZ());
        }).setName("$name");
    """.trimIndent() + "\n"

    // open dir in VSCodium, resolving the launcher per-OS
    fun openInEditor(dir: Path): Result<Unit> = runCatching {
        val windows = System.getProperty("os.name").orEmpty().lowercase().contains("win")
        val cmd = if (windows) listOf("cmd", "/c", "codium", dir.toString())
        else listOf("codium", dir.toString())
        ProcessBuilder(cmd).inheritIO().start()
        Unit
    }
}
